version: 1
disable_existing_loggers: False
formatters:
    detail:
        format: "%(asctime)s - %(name)s - %(message)s"
    onlymessage:
        format: "%(message)s"

handlers:
    file_handler:
        class: logging.FileHandler
        level: DEBUG
        formatter: detail
        filename: ./log
        mode: w

loggers:
    '':
        level: INFO
        handlers: [file_handler]
        propagate: No